# Generated by Django 5.0.6 on 2024-05-28 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_categories_listing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categories",
            old_name="category",
            new_name="categoryName",
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="auctions.categories",
            ),
        ),
    ]
