# Generated by Django 5.0.6 on 2024-06-04 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "auctions",
            "0009_alter_bid_id_alter_categories_id_alter_comments_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="bid",
        ),
    ]
